version: "3.8"

services:
  postgres:
    image: 'postgres'
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tugerente
      - POSTGRES_PASSWORD=software
    volumes:
      - 'tuGerente-app:/var/lib/postgresql/data'

  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - '5050:5000'
    volumes:
      - /usr/src/app
      - ./package.json:/src/package.json
      - ./package-lock.json:/src/package-lock.json
      - notused:/app/node_modules
    environment:
      - DB_USER=postgres
      - PORT=5000
      - DB_HOST=postgres
      - DB_NAME=tugerente
      - DB_PASSWORD=software
      - DB_PORT=5432

volumes:
  tuGerente-app:
  notused:
